DROP TABLE documents
DROP TABLE patents
DROP TABLE cip
DROP TABLE users

CREATE TABLE documents(id INT IDENTITY(1, 1) PRIMARY KEY, patentNum INTEGER, document BINARY)
CREATE TABLE patents(id INT IDENTITY(1, 1) PRIMARY KEY, patentNum INTEGER, patentApplicationNum INTEGER)
CREATE TABLE cip(id INT IDENTITY(1, 1) PRIMARY KEY, patentNum INTEGER, cipApplicationNum INTEGER)

