CREATE TABLE patents(id INT IDENTITY(1, 1) PRIMARY KEY, patentNum INTEGER, filingDate DATE)
CREATE TABLE cip(id INT IDENTITY(1, 1) PRIMARY KEY, CIPNum INTEGER, CIPfilingDate DATE, patentNum INTEGER)
CREATE TABLE users(id INT IDENTITY(1, 1) PRIMARY KEY, firstname VARCHAR, lastname VARCHAR, userID INTEGER)
CREATE TABLE documents(id INT IDENTITY(1, 1) PRIMARY KEY, DocfilingDate INTEGER, document BINARY)